### PR TITLE
Big update with filters + draw position fix + various fixes

### PR DESCRIPTION
**Pull request by flartet**
New options:
data.options.buttonFilter : string : for the filter button display value
data.Lists[x].filter : boolean : activate filter ability for the list
data.Lists[x].keysFilter : array[ strings ] : maybe more for the alternateView mode, in which attribute looking for the filter match ; maybe on normal mode, it should be ["name"], I realize I didn't test it.

I removed all the references to a canvas top margin because there was some unused variables and I found it was not necessary at all. Also removed the bootstrap specific test for the canvas top margin.
I removed the delta calculation to use outerHeight(true) which counts margin in the calculation, it's more accurate and it simplifies the calculation.
I removed effectHover because it was not used at all.
Removed let sep l.355 and 583
I regrouped computeListHeight in a function . I think you could factorize your code using the list index instead of using 'left' or 'right' keyword. .FL-list-0 .FL-list-1 . I did it for the filters div and it's really nice. I didn't change the whole code because maybe some users are using FL-left/right in their devs.

Here is your last commit beautified according to standard rules to be able to compare with my code.
I quickly checked it using https://www.diffchecker.com/diff and it's ok to compare.
[nothing.zip](https://github.com/PhilippeMarcMeyer/FieldsLinker/files/3878858/nothing.zip)

Also, and it doesn't make the diff so readable, I'm sorry for this, I beautified the file and used ESLint to check some rules like ' around strings, semicolons everywhere needed (there was some missing in initial vars). And because indentation was not proper everywhere.

P.S. : I'm not a great GIT user so maybe there are better ways to do this

### CODE REVIEW

**Comment by PhilippeMarcMeyer** [comment]
You did a great Job Flartet :-) Thank you

**Comment by PhilippeMarcMeyer** [comment]
One thing that is wrong with this plugin is that it is not "sealed" you can't run 2 instances in the same page ! That very wrong. I'll have to fix it some day

**Comment by flartet** [comment]
I don't know if it's a problem not to be sealed. I would say the opposite to make it work very well with 2 instances. With proper ajax calls and small lists, it might be interesting for someone this way.

**Comment by PhilippeMarcMeyer** [comment]
Why do you want to put Ajax calls in this plugin ? A dev id free to make his own calls and use the plugin

**Comment by flartet** [comment]
I'm not talking about developing for the plugin.
I was saying that having the ability to put multiple fieldsLinker in the same page could be interesting for a dev who wants to put ajax behind the X fieldsLinkers on the same page. I was only reacting to your remark about making it unique in a page. On the opposite I think it's better to make it isolated with some uuid or user defined id.

**Pull request merged**
